   default: &default
     adapter: postgresql
     encoding: unicode
     pool: 5
     username: postgres
     password: 'tJM93NQXHj2nJOU' # Puedes dejar esto vacío si usas DATABASE_URL
     host: <%= ENV['DATABASE_URL'] %> # O la dirección de tu base de datos en Fly.io

   development:
     <<: *default
     database: ror-javascript-technical-interview_development

   test:
     <<: *default
     database: ror-javascript-technical-interview_test

   production:
     <<: *default
     database: ror-javascript-technical-interview_production